# Generated by Django 5.0.4 on 2024-04-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('programs', models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('children', 'Children'), ('all', 'All')], max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(upload_to='trainer_images')),
            ],
        ),
    ]
