# Generated by Django 5.0.4 on 2024-04-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_availability_alter_trainer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='sessions',
            field=models.CharField(choices=[('half_time', '30 mins to 45 mins'), ('full_time', '60 mins or more'), ('all', 'All')], default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='trainer',
            name='speciality',
            field=models.CharField(choices=[('fisiotherapy', 'Fisiotheraphy'), ('pragnance', 'Pragnance'), ('accessibility', 'Accessibility')], default='all', max_length=50),
        ),
    ]
