# Generated by Django 5.0.4 on 2024-04-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_trainer_sessions_trainer_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='all', upload_to='trainer_images'),
        ),
    ]
