# Generated by Django 5.0.6 on 2024-05-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_remove_trainer_image_url_alter_trainer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='all', upload_to='media'),
        ),
    ]
