# Generated by Django 5.0.6 on 2024-05-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_alter_trainer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='all', upload_to=''),
        ),
    ]
