# Generated by Django 5.0.6 on 2024-05-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='yearly_price',
            field=models.IntegerField(),
        ),
    ]
