# Generated by Django 5.0.6 on 2024-05-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_monthly_price_alter_plan_yearly_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='plan',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
