# Generated by Django 5.0.6 on 2024-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='county',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='town_or_city',
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='plan_price',
            field=models.IntegerField(),
        ),
    ]
