# Generated by Django 5.0.6 on 2024-05-16 23:03

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_billinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='country',
            field=django_countries.fields.CountryField(default=0.003028773346794548, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='county',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='street_address1',
            field=models.CharField(default=0.003028773346794548, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='town_or_city',
            field=models.CharField(default=0.004795557799091368, max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BillingInfo',
        ),
    ]
