# Generated by Django 5.0.6 on 2024-05-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_delete_purchasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
