# Generated by Django 5.0.6 on 2024-05-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
